# syntax=docker/dockerfile:experimental
FROM rhel8-openjdk11-graal-native-base as build
USER root
RUN mkdir /var/app && cd /var/app
COPY . .
RUN --mount=type=cache,target=/root/.m2,rw ./mvnw -Pnative -DskipTests package

FROM redhat/ubi8
RUN mkdir /var/app
COPY --from=build target/*.jar  /var/app/
COPY --from=build target/*.zip  /var/app/
COPY --from=build target/demo  /var/app/
RUN chmod +x /var/app/*.jar \
    && chmod +x /var/app/demo
ENTRYPOINT ["tail", "-f", "/dev/null"]

# docker -v build  --tag mutistage -f Dockerfile-multistage .  --progress=plain