AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Graal Demo API written with SpringBoot with the aws-serverless-java-container library

Globals:
    Function:
        Timeout: 10
        MemorySize: 512

Resources:
  HelloGraalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.graalvm.demo.lambda.LambdaApiRequestHandler::handleRequest
      Runtime: provided
      CodeUri: ../default/run3/demo-0.0.1-SNAPSHOT-native-zip.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 10
      Events:
        GetHelloA:
          Type: Api
          Properties:
            Path: /a
            Method: GET
  LambdaHttpApiRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.graalvm.demo.lambda.LambdaContainerHttpApiRequestFunction::handleRequest
      Runtime: provided
      CodeUri: ../default/run3/demo-0.0.1-SNAPSHOT-native-zip.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 10
      Events:
        GetHelloD:
          Type: Api
          Properties:
            Path: /b
            Method: GET
  PlainRestAPIRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.graalvm.demo.lambda.PlainRestAPIRequestFunctionHandler::handleRequest
      Runtime: provided
      CodeUri: ../default/run3/demo-0.0.1-SNAPSHOT-native-zip.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 10
      Events:
        GetHelloC:
          Type: Api
          Properties:
            Path: /c
            Method: GET
  PlainHttpApiAwsRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.graalvm.demo.lambda.PlainHttpApiAwsRequestFunctionHandler::handleRequest
      Runtime: provided
      CodeUri: ../default/run3/demo-0.0.1-SNAPSHOT-native-zip.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 10
      Events:
        GetHelloD:
          Type: Api
          Properties:
            Path: /d
            Method: GET

Outputs:
    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.us-east-2.amazonaws.com/hello/"